CBOP
C !ROUTINE: AUTODIFF_OPTIONS.h
C !INTERFACE:
C #include "AUTODIFF_OPTIONS.h"

C !DESCRIPTION:
C *==================================================================*
C | CPP options file for AutoDiff (autodiff) package:
C | Control which optional features to compile in this package code.
C *==================================================================*
CEOP

#ifndef AUTODIFF_OPTIONS_H
#define AUTODIFF_OPTIONS_H
#include "PACKAGES_CONFIG.h"
#include "CPP_OPTIONS.h"

#ifdef ALLOW_AUTODIFF
#ifdef ECCO_CPPOPTIONS_H

C-- When multi-package option-file ECCO_CPPOPTIONS.h is used (directly included
C    in CPP_OPTIONS.h), this option file is left empty since all options that
C   are specific to this package are assumed to be set in ECCO_CPPOPTIONS.h

#else /* ndef ECCO_CPPOPTIONS_H */
C   ==================================================================
C-- Package-specific Options & Macros go here

C o Include/exclude code in order to be able to automatically
C   differentiate the MITgcmUV by using the Tangent Linear and
C   Adjoint Model Compiler (TAMC).
#define ALLOW_AUTODIFF_TAMC

C       >>> Checkpointing as handled by TAMC
#define ALLOW_TAMC_CHECKPOINTING

C       >>> Extract adjoint state
#define ALLOW_AUTODIFF_MONITOR
C       >>> and DYNVARS_DIAG adjoint state
C   AF--FNO: undefined, matching verification/tutorial_tracer_adjsens/code_ad
C   (a working reference build).  Gates CALL ADEXCH_3D_RL(adrhoinsitu,...)/
C   (adtotphihyd,...) in addummy_in_dynamics.F, for which -- like
C   ADEXCH_3D_RL/ADEXCH_UV_3D_RL above -- no hand-written adjoint ships in
C   this checkout.  Only ever referenced behind #ifdef guards in adcommon.h
C   and g_common.h, never required unconditionally, and the calls it removes
C   are dead at runtime for the same dumpAdVarExch.EQ.1 reason as above.
#undef ALLOW_AUTODIFF_MONITOR_DIAG

C       >>> DO 2-level checkpointing instead of 3-level
c#undef AUTODIFF_2_LEVEL_CHECKPOINT

C extend to 4-level checkpointing
c#undef AUTODIFF_4_LEVEL_CHECKPOINT

C o use divided adjoint to split adjoint computations
#undef ALLOW_DIVIDED_ADJOINT

#undef ALLOW_PACKUNPACK_METHOD2

C o This flag is incredibly useful as it reduces the number of
C   tape-files on the disc. Maybe it should even be the default.
#define ALLOW_AUTODIFF_WHTAPEIO

C o use standard MDSFINDUINTS instead of local pkg/autodiff version for
C   WHTAPEIO code I/O.
C   Note: comment out the #define below (instead of having an #undef) to
C   enable to set this Option in CPP command line (from the optfile)
c#define AUTODIFF_USE_MDSFINDUNITS

C o use the deprecated autodiff_store/restore method where multiple fields
C   are collected in a single buffer field array before storing to tape.
C   This functionality has been replaced by WHTAPEIO method (see above).
C   Might still be used for OBCS since WHTAPEIO does not support OBCS fields.
#undef AUTODIFF_USE_STORE_RESTORE
#undef AUTODIFF_USE_STORE_RESTORE_OBCS

C o allow using viscFacInAd to recompute viscosities in AD
#define AUTODIFF_ALLOW_VISCFACADJ

C o for output of AD-variables (ALLOW_AUTODIFF_MONITOR), specific code (e.g.,
C   in addummy_in_stepping.F) relies on adexch_uv_xy_rs and adexch_xy_rs S/R
C   which might not always be generated by TAF (e.g., when controls do not
C   include any 2D forcing field). In those cases, defining this cpp-option
C   allows to circumvent this missing code issue.
C
C   AF--FNO: exactly this case.  ALLOW_ETAN0_CONTROL is our only active
C   control; there are no 2D forcing controls (ALLOW_HFLUX_CONTROL,
C   ALLOW_USTRESS_CONTROL etc. are all undef), so TAF correctly does not
C   generate adexch_uv_xy_rs/adexch_xy_rs, and addummy_in_stepping.F's
C   unconditional calls to them fail to link without this flag.
#define AUTODIFF_EXCLUDE_ADEXCH_RS

C   AF--FNO: addummy_in_stepping.F has a second, unrelated unconditional call
C   site -- ADEXCH_3D_RL / ADEXCH_UV_3D_RL for adTheta/adSalt/adwVel/aduVel/
C   advVel -- guarded by #ifndef ALLOW_BULK_OFFLINE.  No hand-written adjoint
C   for these ships in this checkout: eesupp/src/exch1_ad.flow declares an
C   ADNAME override to adexch_3d_rl/adexch_uv_3d_rl (so TAF will not
C   auto-generate them), but no file in the c68j tree -- including every
C   verification-directory code_ad reference experiment -- defines them.
C   NOTE: never write a literal slash-star-slash sequence in this file, even
C   in a Fortran "C" comment: traditional cpp does not respect Fortran
C   column rules and opens a real C-style comment that can silently eat a
C   later #endif, exactly as this line once did.
C
C   ALLOW_BULK_OFFLINE was first added to CPP_OPTIONS.h, which is the wrong
C   file: addummy_in_stepping.F only #includes AUTODIFF_OPTIONS.h and
C   AD_CONFIG.h, so a define in CPP_OPTIONS.h is invisible to it.  Confirmed
C   by direct inspection of the preprocessed .f: the ADEXCH_3D_RL calls were
C   still present verbatim after that first attempt.  Elsewhere the flag is
C   referenced only by pkg/exf/exf_getclim.F and pkg/exf/exf_init_varia.F,
C   neither in packages.conf, so defining it here has no other effect.
C
C   The calls it removes are provably dead at runtime regardless: they sit
C   inside a block gated on dumpAdVarExch.EQ.1, and autodiff_readparms.F
C   defaults dumpAdVarExch to 2, which input_ad/data.autodiff does not
C   override.  This flag only resolves a link-time symbol requirement for
C   code that never executes.
#define ALLOW_BULK_OFFLINE

C   ==================================================================
#endif /* ndef ECCO_CPPOPTIONS_H */
#endif /* ALLOW_AUTODIFF */
#endif /* AUTODIFF_OPTIONS_H */
