"""AUTOGENERATED SKELETON - headers rewritten by hand."""
from __future__ import annotations



import numpy as np


U = slice(0, 15)

def _member_rmse(prediction: np.ndarray, truth: np.ndarray, wet: np.ndarray) -> np.ndarray:
    error = (prediction - truth)[..., wet].reshape(prediction.shape[0], -1)
    return np.sqrt(np.mean(np.square(error), axis=1))

def _member_acc(
    prediction: np.ndarray, truth: np.ndarray, climatology: np.ndarray, wet: np.ndarray
) -> np.ndarray:
    left = (prediction - climatology)[..., wet].reshape(prediction.shape[0], -1).astype(np.float64)
    right = (truth - climatology)[..., wet].reshape(truth.shape[0], -1).astype(np.float64)
    numerator = np.sum(left * right, axis=1)
    denominator = np.sqrt(np.sum(np.square(left), axis=1) * np.sum(np.square(right), axis=1))
    return np.divide(numerator, denominator, out=np.zeros_like(numerator), where=denominator > 0)

GRAVITY_M_S2 = 9.81

THERMAL_EXPANSION_PER_C = 2.0e-4

DRF_M = np.asarray(
    (50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190),
    dtype=np.float64,
)

T_REF_C = np.asarray(
    (30, 27, 24, 21, 18, 15, 13, 11, 9, 7, 6, 5, 4, 3, 2),
    dtype=np.float64,
)

PHIHYD_LEVELS = {
    "phihyd_surface": 0,
    "phihyd_mid": 7,
    "phihyd_bottom": 14,
}

def _vertical_distances() -> tuple[np.ndarray, np.ndarray]:
    """Distances above/below each tracer center used by MITgcm's FD form."""

    interfaces = -np.concatenate(([0.0], np.cumsum(DRF_M)))
    centers = 0.5 * (interfaces[:-1] + interfaces[1:])
    center_spacing = np.diff(centers)
    above = np.empty(DRF_M.size, dtype=np.float64)
    below = np.empty(DRF_M.size, dtype=np.float64)
    above[0] = interfaces[0] - centers[0]
    above[1:] = -0.5 * center_spacing
    below[:-1] = -0.5 * center_spacing
    below[-1] = centers[-1] - interfaces[-1]
    return above, below

def phihyd_from_theta_eta(
    theta_c: np.ndarray,
    eta_m: np.ndarray,
    wet: np.ndarray | None = None,
) -> np.ndarray:
    """Reconstruct total ``PHIHYD`` from temperature and free-surface height.

    Parameters
    ----------
    theta_c
        Temperature with shape ``(..., 15, y, x)`` in degrees Celsius.
    eta_m
        Free-surface height with shape ``(..., y, x)`` in metres.
    wet
        Optional two-dimensional wet mask. Land is set to zero when supplied.

    Returns
    -------
    numpy.ndarray
        Hydrostatic pressure anomaly divided by reference density, with the
        same shape as ``theta_c`` and units m2 s-2.
    """

    theta = np.asarray(theta_c, dtype=np.float64)
    eta = np.asarray(eta_m, dtype=np.float64)
    if theta.ndim < 3 or theta.shape[-3] != DRF_M.size:
        raise ValueError("theta must have shape (..., 15, y, x)")
    if eta.shape != theta.shape[:-3] + theta.shape[-2:]:
        raise ValueError("eta must have shape (..., y, x) matching theta")
    if wet is not None and np.asarray(wet).shape != theta.shape[-2:]:
        raise ValueError("wet mask must match theta's horizontal grid")

    reference_shape = (1,) * (theta.ndim - 3) + (T_REF_C.size, 1, 1)
    density_anomaly_over_reference = -THERMAL_EXPANSION_PER_C * (
        theta - T_REF_C.reshape(reference_shape)
    )
    above, below = _vertical_distances()
    leading_shape = theta.shape[:-3]
    interface_value = np.zeros(leading_shape + theta.shape[-2:], dtype=np.float64)
    baroclinic = np.empty_like(theta)
    for level in range(DRF_M.size):
        layer = density_anomaly_over_reference[..., level, :, :]
        center_value = interface_value + above[level] * GRAVITY_M_S2 * layer
        baroclinic[..., level, :, :] = center_value
        interface_value = center_value + below[level] * GRAVITY_M_S2 * layer

    result = baroclinic + GRAVITY_M_S2 * np.expand_dims(eta, axis=-3)
    if wet is not None:
        result[..., ~np.asarray(wet, dtype=bool)] = 0.0
    return result.astype(np.float32)

def pressure_diagnostics(states: np.ndarray, wet: np.ndarray) -> dict[str, np.ndarray]:
    """Return Bire-facing surface/mid/bottom ``PHIHYD`` from 46-state arrays."""

    values = np.asarray(states)
    if values.ndim != 4 or values.shape[1] != 46:
        raise ValueError("states must have shape (batch, 46, y, x)")
    full = phihyd_from_theta_eta(values[:, 30:45], values[:, 45], wet)
    return {name: full[:, level].copy() for name, level in PHIHYD_LEVELS.items()}

EARTH_RADIUS_M = 6_371_000.0

def _barotropic_streamfunction(states: np.ndarray, wet: np.ndarray) -> np.ndarray:
    """Return meridionally integrated transport streamfunction in Sv."""

    dy_m = EARTH_RADIUS_M * np.deg2rad(1.0)
    depth_integrated_u = np.sum(states[:, U] * DRF_M[None, :, None, None], axis=1)
    value = np.cumsum(-depth_integrated_u * dy_m, axis=1) / 1.0e6
    value[:, ~wet] = 0.0
    return value.astype(np.float32)

V = slice(15, 30)

SVERDRUP_M3_S = 1.0e6


def depth_integrated_transport(states: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Return barotropic transports ``(U_BT, V_BT)`` in m2 s-1.

    ``states`` has shape ``(batch, 46, y, x)``; each output is ``(batch, y, x)``.
    """

    values = np.asarray(states, dtype=np.float64)
    if values.ndim != 4 or values.shape[1] != 46:
        raise ValueError("states must have shape (batch, 46, y, x)")
    thickness = DRF_M[None, :, None, None]
    return (
        np.sum(values[:, U] * thickness, axis=1),
        np.sum(values[:, V] * thickness, axis=1),
    )


def streamfunction_from_u(transport_x: np.ndarray, wet: np.ndarray, dy_m: float) -> np.ndarray:
    """Meridional cumulative integral of ``-U_BT``: the published reconstruction."""

    value = np.cumsum(-np.asarray(transport_x, dtype=np.float64) * dy_m, axis=1)
    value[:, ~wet] = 0.0
    return (value / SVERDRUP_M3_S).astype(np.float32)


def streamfunction_from_v(transport_y: np.ndarray, wet: np.ndarray, dx_m: np.ndarray) -> np.ndarray:
    """Zonal cumulative integral of ``+V_BT``, the independent counterpart.

    Uses the same sign convention as :func:`streamfunction_from_u`, for which
    ``u = -d(psi)/dy`` and ``v = +d(psi)/dx``.
    """

    spacing = np.asarray(dx_m, dtype=np.float64)
    value = np.cumsum(np.asarray(transport_y, dtype=np.float64) * spacing[None], axis=2)
    value[:, ~wet] = 0.0
    return (value / SVERDRUP_M3_S).astype(np.float32)


def streamfunction_least_squares(
    transport_x: np.ndarray,
    transport_y: np.ndarray,
    wet: np.ndarray,
    dx_m: np.ndarray,
    dy_m: float,
) -> np.ndarray:
    """Least-squares streamfunction using both transports.

    Minimizes ``|d(psi)/dy + U_BT|^2 + |d(psi)/dx - V_BT|^2`` over wet cells,
    with the gauge fixed by forcing the wet-cell mean to zero.  Solved on the
    face-difference stencil, so no derivative of the transport is taken and the
    two components are weighted equally per face.
    """

    from scipy.sparse import coo_matrix
    from scipy.sparse.linalg import lsqr

    mask = np.asarray(wet, dtype=bool)
    spacing = np.asarray(dx_m, dtype=np.float64)
    index = -np.ones(mask.shape, dtype=np.int64)
    index[mask] = np.arange(int(mask.sum()))
    unknowns = int(mask.sum())

    rows: list[int] = []
    cols: list[int] = []
    data: list[float] = []
    equation = 0
    pairs: list[tuple[tuple, tuple, str]] = []
    # Meridional faces: psi[j+1,i] - psi[j,i] = -U_BT_face * dy
    both = mask[:-1, :] & mask[1:, :]
    for j, i in zip(*np.nonzero(both)):
        rows += [equation, equation]
        cols += [index[j + 1, i], index[j, i]]
        data += [1.0, -1.0]
        pairs.append(((j, i), (j + 1, i), "y"))
        equation += 1
    # Zonal faces: psi[j,i+1] - psi[j,i] = +V_BT_face * dx
    both = mask[:, :-1] & mask[:, 1:]
    for j, i in zip(*np.nonzero(both)):
        rows += [equation, equation]
        cols += [index[j, i + 1], index[j, i]]
        data += [1.0, -1.0]
        pairs.append(((j, i), (j, i + 1), "x"))
        equation += 1
    # Gauge: the wet-cell mean is zero, so the null space is removed.
    rows += [equation] * unknowns
    cols += list(range(unknowns))
    data += [1.0 / unknowns] * unknowns
    equation += 1
    operator = coo_matrix((data, (rows, cols)), shape=(equation, unknowns)).tocsr()

    batch = np.asarray(transport_x, dtype=np.float64).shape[0]
    result = np.zeros((batch,) + mask.shape, dtype=np.float64)
    for member in range(batch):
        u_bt = np.asarray(transport_x, dtype=np.float64)[member]
        v_bt = np.asarray(transport_y, dtype=np.float64)[member]
        target = np.empty(equation, dtype=np.float64)
        for row, (low, high, axis) in enumerate(pairs):
            if axis == "y":
                face = 0.5 * (u_bt[low] + u_bt[high])
                target[row] = -face * dy_m
            else:
                face = 0.5 * (v_bt[low] + v_bt[high])
                target[row] = face * 0.5 * (spacing[low] + spacing[high])
        target[-1] = 0.0
        solution = lsqr(operator, target, atol=1e-12, btol=1e-12, iter_lim=20000)[0]
        result[member][mask] = solution
    return (result / SVERDRUP_M3_S).astype(np.float32)


def derived_fields(states: np.ndarray, wet: np.ndarray) -> dict[str, np.ndarray]:
    """Return the seven Bire-facing two-dimensional diagnostics."""

    fields = {
        "surface_speed": np.sqrt(np.square(states[:, 0]) + np.square(states[:, 15])),
        "sst": states[:, 30].copy(),
        "ssh": states[:, 45].copy(),
        **pressure_diagnostics(states, wet),
        "streamfunction": _barotropic_streamfunction(states, wet),
    }
    for value in fields.values():
        value[:, ~wet] = 0.0
    return fields

