"""AUTOGENERATED SKELETON - headers rewritten by hand."""
from __future__ import annotations

import math
from pathlib import Path
from typing import Any
from dataclasses import asdict, dataclass, field

import numpy as np

from .runtime import FNO, functional, nn, torch
from .runtime import STATE_CHANNEL_COUNT, STATIC_FEATURES, require_model_a_runtime
from .dataset import ModelCSuccessorArchitecture

RETAINED_STATIC_FEATURES = (
    "wind_stress_x",
    "wet_mask",
    "distance_to_wall_normalized",
)

RETAINED_STATIC_INDICES = tuple(
    STATIC_FEATURES.index(name) for name in RETAINED_STATIC_FEATURES
)

EXTERNAL_INPUT_CHANNELS = STATE_CHANNEL_COUNT + len(RETAINED_STATIC_FEATURES)

POSITIONAL_CHANNELS = 2

LIFTING_INPUT_CHANNELS = EXTERNAL_INPUT_CHANNELS + POSITIONAL_CHANNELS

README_NAME = "README.md"

MANIFEST_NAME = "manifest.json"

CHECKPOINT_DIRECTORY = "training_checkpoints"

class BireAlignedFullStateError(RuntimeError):
    """Raised when the Bire-aligned full-state arm violates its contract."""

class BireAlignedDivergenceError(BireAlignedFullStateError):
    """Raised when the declared learning rate produces a non-finite update."""

@dataclass(frozen=True)
class BireAlignedArchitecture:
    """Three-block Bire FNO over the retained 46-channel state.

    ``in_channels`` counts the *external* inputs only.  The two deterministic
    Bire position channels are appended inside the model, immediately before
    lifting, so the lifting network still sees 51 channels.
    """

    in_channels: int = EXTERNAL_INPUT_CHANNELS
    out_channels: int = STATE_CHANNEL_COUNT
    positional_channels: int = POSITIONAL_CHANNELS
    lifting_in_channels: int = LIFTING_INPUT_CHANNELS
    grid_shape: tuple[int, int] = (62, 62)
    n_modes: tuple[int, int] = (24, 16)
    hidden_channels: int = 128
    n_layers: int = 3
    lifting_channel_ratio: int = 2
    projection_channel_ratio: int = 2
    channel_mlp_expansion: float = 4.0
    channel_mlp_dropout: float = 0.0
    domain_padding: float = 0.1
    positional_embedding: str | None = None
    use_channel_mlp: bool = True
    pointwise_layer_norm: bool = True
    local_kernel_size: int | None = None
    fno_block_precision: str = "full"
    factorization: str | None = None

    def __post_init__(self) -> None:
        object.__setattr__(
            self, "n_modes", tuple(int(value) for value in self.n_modes)
        )
        object.__setattr__(
            self, "grid_shape", tuple(int(value) for value in self.grid_shape)
        )
        if (
            self.in_channels != EXTERNAL_INPUT_CHANNELS
            or self.out_channels != STATE_CHANNEL_COUNT
            or self.positional_channels != POSITIONAL_CHANNELS
            or self.lifting_in_channels != LIFTING_INPUT_CHANNELS
        ):
            raise BireAlignedFullStateError(
                "the Bire-aligned arm maps 46 state + 3 static (+2 position) -> 46"
            )
        if self.grid_shape != (62, 62) or self.n_modes != (24, 16):
            raise BireAlignedFullStateError(
                "the Bire-aligned arm keeps the 62x62 grid and 24x16 modes"
            )
        if self.n_layers != 3:
            raise BireAlignedFullStateError(
                "the Bire-aligned arm uses exactly three FNO blocks"
            )
        if self.hidden_channels != 128 or self.channel_mlp_expansion != 4.0:
            raise BireAlignedFullStateError(
                "the Bire-aligned arm keeps width 128 and the 4C Channel MLP"
            )
        if self.lifting_channel_ratio != 2 or self.projection_channel_ratio != 2:
            raise BireAlignedFullStateError(
                "the Bire-aligned arm keeps lifting and projection width 256"
            )
        if self.domain_padding != 0.1 or not self.use_channel_mlp:
            raise BireAlignedFullStateError(
                "the Bire-aligned arm keeps 10% padding and the Channel MLP"
            )
        if self.channel_mlp_dropout != 0.0:
            raise BireAlignedFullStateError(
                "the first clean Bire-aligned test freezes Channel MLP dropout at zero"
            )
        if self.positional_embedding is not None:
            raise BireAlignedFullStateError(
                "position enters only through the Bire sine/cosine encoder"
            )
        if not self.pointwise_layer_norm:
            raise BireAlignedFullStateError(
                "Bire normalizes channel-wise after both mixing operations"
            )
        if self.local_kernel_size is not None:
            raise BireAlignedFullStateError(
                "the external 3x3 raw-input branch is removed in this arm"
            )
        if self.fno_block_precision != "full" or self.factorization is not None:
            raise BireAlignedFullStateError(
                "the Bire-aligned arm remains a dense float32 FNO"
            )

    @property
    def layer_norm_count(self) -> int:
        return 2 * self.n_layers

    def to_dict(self) -> dict[str, Any]:
        result = asdict(self)
        result["n_modes"] = list(self.n_modes)
        result["grid_shape"] = list(self.grid_shape)
        return result

def retained_features(batch: Any) -> Any:
    """Drop the two linear coordinate channels from a 51-channel batch."""

    if batch.ndim != 4 or batch.shape[1] != STATE_CHANNEL_COUNT + len(
        STATIC_FEATURES
    ):
        raise ValueError("the Bire-aligned arm reduces N,51,Y,X inputs")
    index = torch.as_tensor(
        [STATE_CHANNEL_COUNT + offset for offset in RETAINED_STATIC_INDICES],
        dtype=torch.long,
        device=batch.device,
    )
    return torch.cat(
        (batch[:, :STATE_CHANNEL_COUNT], batch.index_select(1, index)),
        dim=1,
    )

ARM_IDS = ("layernorm", "dropout", "layernorm_dropout")

@dataclass(frozen=True)
class RegularizationArm:
    """One factorial arm in the frozen LayerNorm/dropout comparison."""

    arm_id: str
    pointwise_layer_norm: bool
    channel_mlp_dropout: float

    def __post_init__(self) -> None:
        if self.arm_id not in ARM_IDS:
            raise ValueError("unknown Bire regularization arm")
        if self.channel_mlp_dropout not in (0.0, 0.5):
            raise ValueError("dropout control must use zero or archived default 0.5")

if nn is not None:

    class PointwiseChannelLayerNorm(nn.Module):
        """LayerNorm over channels independently at every grid point."""

        def __init__(self, channels: int, epsilon: float = 1.0e-5) -> None:
            super().__init__()
            self.channels = int(channels)
            self.epsilon = float(epsilon)
            self.weight = nn.Parameter(torch.ones(self.channels))
            self.bias = nn.Parameter(torch.zeros(self.channels))

        def forward(self, value: Any) -> Any:
            if value.ndim != 4 or value.shape[1] != self.channels:
                raise ValueError("pointwise LayerNorm expects N,C,Y,X")
            channels_last = value.permute(0, 2, 3, 1)
            normalized = functional.layer_norm(
                channels_last,
                (self.channels,),
                self.weight,
                self.bias,
                self.epsilon,
            )
            return normalized.permute(0, 3, 1, 2)


    class BireRegularizedDirectFNO(nn.Module):
        """The fixed width-128 Model C with explicit Bire regularizers."""

        def __init__(
            self,
            architecture: ModelCSuccessorArchitecture,
            arm: RegularizationArm,
        ) -> None:
            super().__init__()
            self.architecture = architecture
            self.arm = arm
            self.fno = FNO(
                n_modes=architecture.n_modes,
                in_channels=architecture.in_channels,
                out_channels=architecture.out_channels,
                hidden_channels=architecture.hidden_channels,
                n_layers=architecture.n_layers,
                lifting_channel_ratio=architecture.lifting_channel_ratio,
                projection_channel_ratio=architecture.projection_channel_ratio,
                positional_embedding=architecture.positional_embedding,
                use_channel_mlp=architecture.use_channel_mlp,
                channel_mlp_dropout=arm.channel_mlp_dropout,
                channel_mlp_expansion=architecture.channel_mlp_expansion,
                domain_padding=architecture.domain_padding,
                fno_block_precision=architecture.fno_block_precision,
                factorization=architecture.factorization,
            )
            if arm.pointwise_layer_norm:
                self.fno.fno_blocks.norm = nn.ModuleList(
                    [
                        PointwiseChannelLayerNorm(
                            architecture.hidden_channels,
                        )
                        for _ in range(architecture.n_layers * 2)
                    ]
                )
            self.local = nn.Conv2d(
                architecture.in_channels,
                architecture.out_channels,
                kernel_size=architecture.local_kernel_size,
                padding=architecture.local_kernel_size // 2,
            )

        def forward(self, features: Any) -> Any:
            if (
                features.ndim != 4
                or features.shape[1] != self.architecture.in_channels
            ):
                raise ValueError("regularized Model C expects N,51,Y,X")
            return self.fno(features) + self.local(features)

else:  # pragma: no cover
    PointwiseChannelLayerNorm = None  # type: ignore[assignment,misc]
    BireRegularizedDirectFNO = None  # type: ignore[assignment,misc]

def direct_state_unroll(
    model: Any,
    features: Any,
    wet: Any,
    steps: int,
) -> Any:
    """Autoregress a direct normalized future-state map."""

    if steps <= 0:
        raise ValueError("direct-state rollout needs at least one step")
    current = features[:, :STATE_CHANNEL_COUNT]
    static = features[:, STATE_CHANNEL_COUNT:]
    predictions = []
    for _ in range(steps):
        current = model(torch.cat((current, static), dim=1)) * wet
        predictions.append(current)
    return torch.stack(predictions, dim=1)

@dataclass
class PointwiseDirectStepper:
    """Evaluation adapter for a direct map with pointwise normalization."""

    model: Any
    device: Any
    wet: np.ndarray
    mean: np.ndarray
    scale: np.ndarray
    wind_mean: float
    wind_scale: float

    def normalized_state(self, physical: np.ndarray) -> Any:
        value = (physical - self.mean[None]) / self.scale[None]
        value[:, :, ~self.wet] = 0.0
        return torch.from_numpy(
            np.ascontiguousarray(value, dtype=np.float32)
        ).to(device=self.device, dtype=torch.float32)

    def normalized_static(self, static: Any, experiments: np.ndarray) -> Any:
        value = np.stack(
            [
                np.asarray(static[int(experiment)], dtype=np.float32)
                for experiment in experiments
            ]
        )
        value[:, 0] = (value[:, 0] - self.wind_mean) / self.wind_scale
        value[:, 0, ~self.wet] = 0.0
        return torch.from_numpy(np.ascontiguousarray(value)).to(
            device=self.device,
            dtype=torch.float32,
        )

    def step(self, current: Any, static: Any) -> Any:
        wet = torch.from_numpy(self.wet.astype(np.float32))[None, None].to(
            self.device
        )
        return self.model(torch.cat((current, static), dim=1)) * wet

    def physical(self, normalized: Any) -> np.ndarray:
        value = normalized.detach().cpu().numpy()
        value = value * self.scale[None] + self.mean[None]
        value[:, :, ~self.wet] = 0.0
        return np.ascontiguousarray(value, dtype=np.float32)

if nn is not None:

    class BirePositionalEncoding(nn.Module):
        """Deterministic ``oceanfourcast.PosEmbed`` position channels.

        Each direction contributes one channel whose entries alternate between
        sine and cosine of ``pi/(2 N) * index``::

            p(j) = sin(w_j) for even j,  cos(w_j) for odd j.

        The two fields are concatenated after the external inputs, in the
        published order ``(x, p_x, p_y)``, immediately before lifting.  They are
        constants, so they are registered as non-persistent buffers and never
        enter a checkpoint.
        """

        def __init__(self, height: int, width: int) -> None:
            super().__init__()
            self.height = int(height)
            self.width = int(width)
            self.register_buffer(
                "position_x",
                self._axis(self.width).view(1, 1, 1, self.width).expand(
                    1, 1, self.height, self.width
                ).contiguous(),
                persistent=False,
            )
            self.register_buffer(
                "position_y",
                self._axis(self.height).view(1, 1, self.height, 1).expand(
                    1, 1, self.height, self.width
                ).contiguous(),
                persistent=False,
            )

        @staticmethod
        def _axis(size: int) -> Any:
            frequency = math.pi / (2 * size) * torch.arange(
                size,
                dtype=torch.float32,
            )
            grid = torch.zeros(size, dtype=torch.float32)
            grid[::2] = torch.sin(frequency[::2])
            grid[1::2] = torch.cos(frequency[1::2])
            return grid

        def forward(self, value: Any) -> Any:
            if value.ndim != 4 or value.shape[-2:] != (self.height, self.width):
                raise ValueError("Bire position encoder expects N,C,62,62")
            batch = value.shape[0]
            return torch.cat(
                (
                    value,
                    self.position_x.expand(batch, -1, -1, -1),
                    self.position_y.expand(batch, -1, -1, -1),
                ),
                dim=1,
            )

    class BireAlignedFullStateFNO(nn.Module):
        """Three-block Bire FNO with six pointwise LayerNorms and no 3x3 branch.

        The pointwise residual ``W h`` around each truncated spectral operator is
        NeuralOperator's default ``fno_skip="linear"`` path and is retained; only
        the external raw-input-to-output convolution is removed.
        """

        def __init__(self, architecture: BireAlignedArchitecture) -> None:
            super().__init__()
            self.architecture = architecture
            self.positional_encoding = BirePositionalEncoding(
                *architecture.grid_shape
            )
            self.fno = FNO(
                n_modes=architecture.n_modes,
                in_channels=architecture.lifting_in_channels,
                out_channels=architecture.out_channels,
                hidden_channels=architecture.hidden_channels,
                n_layers=architecture.n_layers,
                lifting_channel_ratio=architecture.lifting_channel_ratio,
                projection_channel_ratio=architecture.projection_channel_ratio,
                positional_embedding=architecture.positional_embedding,
                use_channel_mlp=architecture.use_channel_mlp,
                channel_mlp_dropout=architecture.channel_mlp_dropout,
                channel_mlp_expansion=architecture.channel_mlp_expansion,
                domain_padding=architecture.domain_padding,
                fno_block_precision=architecture.fno_block_precision,
                factorization=architecture.factorization,
            )
            self.fno.fno_blocks.norm = nn.ModuleList(
                [
                    PointwiseChannelLayerNorm(architecture.hidden_channels)
                    for _ in range(architecture.layer_norm_count)
                ]
            )

        def forward(self, features: Any) -> Any:
            if (
                features.ndim != 4
                or features.shape[1] != self.architecture.in_channels
            ):
                raise ValueError("Bire-aligned Model C expects N,49,Y,X")
            return self.fno(self.positional_encoding(features))

else:  # pragma: no cover - environment dependent
    BirePositionalEncoding = None  # type: ignore[assignment,misc]
    BireAlignedFullStateFNO = None  # type: ignore[assignment,misc]

def build_bire_aligned_model(architecture: BireAlignedArchitecture) -> Any:
    """Build the Bire-aligned map, matching ``build_successor``'s signature."""

    require_model_a_runtime()
    if BireAlignedFullStateFNO is None:  # pragma: no cover
        raise RuntimeError("the Bire-aligned arm requires PyTorch")
    return BireAlignedFullStateFNO(architecture)

class BireAlignedStepper(PointwiseDirectStepper):
    """Evaluation adapter that supplies only the three retained static fields."""

    def normalized_static(self, static: Any, experiments: np.ndarray) -> Any:
        value = super().normalized_static(static, experiments)
        index = torch.as_tensor(
            RETAINED_STATIC_INDICES,
            dtype=torch.long,
            device=value.device,
        )
        return value.index_select(1, index)

