"""AUTOGENERATED SKELETON - headers rewritten by hand."""
from __future__ import annotations

from pathlib import Path
from typing import Any
from dataclasses import asdict, dataclass, field


from .runtime import torch
from .runtime import GROUP_SLICES, STATE_CHANNEL_COUNT

try:  # Keep documentation-only imports usable without the optional ML stack.
    import torch
except (ImportError, OSError):  # pragma: no cover - environment dependent
    torch = None  # type: ignore[assignment]

MODEL_C_LOSS_V1_CONTRACT_SHA256 = (
    "19000a1426ea928db7799c82a73ce071a874911eb7e1df50bd276582ec30b5f9"
)

@dataclass(frozen=True)
class ModelCLossConfig:
    """Balanced objective frozen from the training-only C1a gradient audit."""

    rollout_steps: int = 3
    increment_weight: float = 0.001
    rollout_weight: float = 0.15
    spectral_weight: float = 0.00001
    boundary_weight: float = 0.065
    spectral_bins: int = 12
    western_boundary_width: int = 4

    def __post_init__(self) -> None:
        weights = (
            self.increment_weight,
            self.rollout_weight,
            self.spectral_weight,
            self.boundary_weight,
        )
        if self.rollout_steps != 3:
            raise ValueError("Model C uses the predeclared three-step rollout")
        if any(value <= 0 for value in weights):
            raise ValueError("every frozen Model C loss term must have positive weight")
        if self.spectral_bins <= 1 or self.western_boundary_width <= 0:
            raise ValueError("Model C needs spectral bins and a positive boundary width")

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

def _validate_state_pair(prediction: Any, target: Any, mask: Any) -> None:
    if prediction.shape != target.shape or prediction.ndim != 4:
        raise ValueError("Model C prediction and target must share N,C,Y,X shape")
    if prediction.shape[1] != STATE_CHANNEL_COUNT:
        raise ValueError("Model C loss requires the declared 46 state channels")
    if mask.shape != (1, 1, *prediction.shape[-2:]):
        raise ValueError("Model C masks must be shaped 1,1,Y,X")

def group_relative_l2_terms(
    prediction: Any,
    target: Any,
    mask: Any,
    *,
    epsilon: float = 1.0e-12,
) -> dict[str, Any]:
    """Return equal-status physical-group state errors."""

    _validate_state_pair(prediction, target, mask)
    terms: dict[str, Any] = {}
    for name, channels in GROUP_SLICES.items():
        error = (prediction[:, channels] - target[:, channels]).square() * mask
        reference = target[:, channels].square() * mask
        numerator = error.sum(dim=(1, 2, 3))
        denominator = reference.sum(dim=(1, 2, 3)).clamp_min(epsilon)
        terms[name] = torch.sqrt(numerator / denominator).mean()
    terms["mean"] = torch.stack(list(terms.values())).mean()
    return terms

def group_increment_nrmse_terms(
    prediction_increment: Any,
    target_increment: Any,
    mask: Any,
    increment_scale: Any,
    *,
    epsilon: float = 1.0e-12,
) -> dict[str, Any]:
    """Return per-group RMSE after training-only per-channel increment scaling."""

    _validate_state_pair(prediction_increment, target_increment, mask)
    if increment_scale.shape not in ((STATE_CHANNEL_COUNT,), (1, STATE_CHANNEL_COUNT, 1, 1)):
        raise ValueError("Model C increment scale must contain exactly 46 channel values")
    scale = increment_scale.reshape(1, STATE_CHANNEL_COUNT, 1, 1).clamp_min(epsilon)
    standardized = (prediction_increment - target_increment) / scale
    terms: dict[str, Any] = {}
    wet_count = mask.sum().clamp_min(1.0)
    for name, channels in GROUP_SLICES.items():
        channel_count = channels.stop - channels.start
        squared = standardized[:, channels].square() * mask
        terms[name] = torch.sqrt(
            squared.sum(dim=(1, 2, 3)) / (wet_count * channel_count)
        ).mean()
    terms["mean"] = torch.stack(list(terms.values())).mean()
    return terms

def wet_rectangle_bounds(mask: Any) -> tuple[int, int, int, int]:
    """Return the exact rectangular wet basin or reject unsupported interior holes."""

    if mask.ndim != 4 or mask.shape[:2] != (1, 1):
        raise ValueError("Model C wet mask must be shaped 1,1,Y,X")
    wet = mask[0, 0] > 0
    rows, columns = torch.where(wet)
    if rows.numel() == 0:
        raise ValueError("Model C wet mask is empty")
    y0, y1 = int(rows.min()), int(rows.max()) + 1
    x0, x1 = int(columns.min()), int(columns.max()) + 1
    if not bool(wet[y0:y1, x0:x1].all().item()):
        raise ValueError("tapered Model C spectrum requires an exact rectangular wet basin")
    if bool(wet[:y0].any() or wet[y1:].any() or wet[:, :x0].any() or wet[:, x1:].any()):
        raise ValueError("wet cells exist outside the inferred Model C spectral rectangle")
    return y0, y1, x0, x1

def tapered_group_spectral_loss(
    prediction: Any,
    target: Any,
    wet_mask: Any,
    *,
    bins: int = 12,
    epsilon: float = 1.0e-12,
) -> Any:
    """Compare group-balanced radial amplitudes after cropping and Hann tapering."""

    _validate_state_pair(prediction, target, wet_mask)
    if bins <= 1:
        raise ValueError("Model C spectral loss needs at least two bins")
    y0, y1, x0, x1 = wet_rectangle_bounds(wet_mask)

    def amplitudes(value: Any, channels: slice) -> Any:
        field = value[:, channels, y0:y1, x0:x1]
        field = field - field.mean(dim=(-2, -1), keepdim=True)
        window_y = torch.hann_window(
            field.shape[-2], periodic=False, dtype=field.dtype, device=field.device
        )
        window_x = torch.hann_window(
            field.shape[-1], periodic=False, dtype=field.dtype, device=field.device
        )
        field = field * window_y[:, None] * window_x[None, :]
        power = torch.fft.rfft2(field, norm="ortho").abs().square()
        fy = torch.fft.fftfreq(field.shape[-2], device=field.device)
        fx = torch.fft.rfftfreq(field.shape[-1], device=field.device)
        radius = torch.sqrt(fy[:, None].square() + fx[None, :].square())
        valid = radius > 0
        indices = (
            torch.floor(radius[valid] / radius.max() * bins).to(torch.long).clamp_max(bins - 1)
        )
        flattened = power[..., valid]
        spectrum = torch.zeros(
            (*power.shape[:2], bins), device=field.device, dtype=field.dtype
        )
        spectrum.scatter_add_(2, indices[None, None].expand_as(flattened), flattened)
        counts = torch.bincount(indices, minlength=bins).to(field.dtype).clamp_min(1.0)
        return torch.sqrt(spectrum / counts[None, None] + epsilon)

    losses = []
    for channels in GROUP_SLICES.values():
        predicted = amplitudes(prediction, channels)
        expected = amplitudes(target, channels)
        numerator = (predicted - expected).square().sum(dim=(1, 2))
        denominator = expected.square().sum(dim=(1, 2)).clamp_min(epsilon)
        losses.append(torch.sqrt(numerator / denominator).mean())
    return torch.stack(losses).mean()

def model_c_loss_terms(
    predictions: Any,
    targets: Any,
    present: Any,
    wet: Any,
    western_boundary: Any,
    increment_scale: Any,
    config: ModelCLossConfig,
) -> dict[str, Any]:
    """Compute the complete balanced Model C objective and audit components."""

    if predictions.shape != targets.shape or predictions.ndim != 5:
        raise ValueError("Model C rollouts must share N,S,C,Y,X shape")
    if predictions.shape[1] != config.rollout_steps or present.shape != predictions[:, 0].shape:
        raise ValueError("Model C loss received an inconsistent rollout or present state")

    state_groups = group_relative_l2_terms(predictions[:, 0], targets[:, 0], wet)
    increment_groups = group_increment_nrmse_terms(
        predictions[:, 0] - present,
        targets[:, 0] - present,
        wet,
        increment_scale,
    )
    rollout = torch.stack(
        [
            group_relative_l2_terms(predictions[:, step], targets[:, step], wet)["mean"]
            for step in range(1, config.rollout_steps)
        ]
    ).mean()

    spectral_values = []
    previous_prediction = present
    previous_target = present
    for step in range(config.rollout_steps):
        spectral_values.append(
            tapered_group_spectral_loss(
                predictions[:, step] - previous_prediction,
                targets[:, step] - previous_target,
                wet,
                bins=config.spectral_bins,
            )
        )
        previous_prediction = predictions[:, step]
        previous_target = targets[:, step]
    spectral = torch.stack(spectral_values).mean()
    boundary = torch.stack(
        [
            group_relative_l2_terms(
                predictions[:, step], targets[:, step], western_boundary
            )["mean"]
            for step in range(config.rollout_steps)
        ]
    ).mean()
    total = (
        state_groups["mean"]
        + config.increment_weight * increment_groups["mean"]
        + config.rollout_weight * rollout
        + config.spectral_weight * spectral
        + config.boundary_weight * boundary
    )
    result = {
        "total": total,
        "state": state_groups["mean"],
        "increment": increment_groups["mean"],
        "rollout": rollout,
        "spectral": spectral,
        "boundary": boundary,
    }
    result.update({f"state_{name}": state_groups[name] for name in GROUP_SLICES})
    result.update({f"increment_{name}": increment_groups[name] for name in GROUP_SLICES})
    return result



def model_c_loss_config(version: str = "v1") -> ModelCLossConfig:
    """Return the certified three-step objective.

    Kept as an explicit accessor so the six-step fine-tune configuration in
    :mod:`oceanfno.train` can be compared against it field by field, and so the
    guard that the certified version still refuses `rollout_steps != 3` has
    something to call.
    """

    if version != "v1":
        raise ValueError("this tree carries only Model C loss v1 and its six-step fine-tune")
    return ModelCLossConfig()
