"""AUTOGENERATED SKELETON - headers rewritten by hand."""
from __future__ import annotations

import copy
import hashlib
import json
import random
import time
from pathlib import Path
from typing import Any, Sequence

from importlib import metadata

import numpy as np
import zarr


def _json_sha256(value: Any) -> str:
    encoded = json.dumps(
        value,
        sort_keys=True,
        separators=(",", ":"),
        allow_nan=False,
    ).encode()
    return hashlib.sha256(encoded).hexdigest()

try:  # Keep documentation-only imports working on login nodes without ML packages.
    import torch
    from torch import nn
    import torch.nn.functional as functional
    from torch.utils.data import DataLoader, Dataset
    from neuralop.models import FNO
except (ImportError, OSError):  # pragma: no cover - environment dependent
    torch = None  # type: ignore[assignment]
    nn = None  # type: ignore[assignment]
    functional = None  # type: ignore[assignment]
    DataLoader = None  # type: ignore[assignment]
    Dataset = object  # type: ignore[assignment,misc]
    FNO = None  # type: ignore[assignment]

def require_model_a_runtime() -> None:
    """Verify the maintained, pinned NeuralOperator runtime used by Model A."""

    if torch is None or nn is None or FNO is None or DataLoader is None:
        raise RuntimeError("Model A requires the project PyTorch and NeuralOperator 2.0.0 environment")
    try:
        version = metadata.version("neuraloperator")
    except metadata.PackageNotFoundError as exc:  # pragma: no cover - installation failure
        raise RuntimeError("Model A requires the project PyTorch and NeuralOperator 2.0.0 environment") from exc
    if version != "2.0.0":
        raise RuntimeError(f"Model A is pinned to neuraloperator 2.0.0, found {version}")

def seed_everything(seed: int) -> None:
    """Make acceptance-gate initialization and batch order reproducible."""

    require_model_a_runtime()
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.benchmark = False
    torch.backends.cudnn.deterministic = True
    torch.use_deterministic_algorithms(True, warn_only=True)

def _checkpoint_state_dict(model: Any) -> dict[str, Any]:
    """Copy only loadable parameters from NeuralOperator's augmented state dict."""

    # neuraloperator 2.0's FNO includes a top-level ``_metadata`` value in its
    # state dictionary.  PyTorch's load_state_dict treats it as an unexpected
    # parameter key, so it must not enter a portable experiment checkpoint.
    return copy.deepcopy({key: value for key, value in model.state_dict().items() if key != "_metadata"})

HORIZON_DAYS = 10

def state_channels(nr: int) -> tuple[str, ...]:
    """Names for x=[U_1:Nr,V_1:Nr,Theta_1:Nr,eta]."""

    return tuple(
        [f"U_{level:02d}" for level in range(1, nr + 1)]
        + [f"V_{level:02d}" for level in range(1, nr + 1)]
        + [f"Theta_{level:02d}" for level in range(1, nr + 1)]
        + ["Eta"]
    )

STATE_CHANNELS = state_channels(15)

STATIC_FEATURES = (
    "wind_stress_x",
    "longitude_normalized",
    "latitude_normalized",
    "wet_mask",
    "distance_to_wall_normalized",
)

STATE_CHANNEL_COUNT = len(STATE_CHANNELS)

GROUP_SLICES = {
    "u": slice(0, 15),
    "v": slice(15, 30),
    "temperature": slice(30, 45),
    "ssh": slice(45, 46),
}

AUDIT_TERMS = (
    "total",
    "state",
    "increment",
    "rollout",
    "spectral",
    "boundary",
    *(f"state_{name}" for name in GROUP_SLICES),
    *(f"increment_{name}" for name in GROUP_SLICES),
)

def _file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()

def _device(name: str) -> Any:
    if name == "auto":
        name = "cuda" if torch.cuda.is_available() else "cpu"
    if name == "cuda" and not torch.cuda.is_available():
        raise RuntimeError("Model C CUDA overfit requested without a visible GPU")
    return torch.device(name)

WIND_FEATURE_INDEX = STATIC_FEATURES.index("wind_stress_x")

STATE_CHANNEL_COUNT = len(STATE_CHANNELS)

STATIC_CHANNEL_COUNT = len(STATIC_FEATURES)

def _normalization_from_group(group: Any) -> tuple[np.ndarray, np.ndarray, np.ndarray, float, float]:
    if tuple(group.attrs.get("state_channels", ())) != STATE_CHANNELS:
        raise ValueError("dataset state-channel order is not the declared 46-channel AF contract")
    if tuple(group.attrs.get("static_features", ())) != STATIC_FEATURES:
        raise ValueError("dataset static-feature order is not the declared Model A contract")
    mean = np.asarray(group["state_mean"][:], dtype=np.float32)
    scale = np.asarray(group["state_scale"][:], dtype=np.float32)
    wet = np.asarray(group["wet_mask"][:], dtype=bool)
    if mean.shape != (STATE_CHANNEL_COUNT,) or scale.shape != mean.shape or np.any(scale <= 0):
        raise ValueError("invalid Model A state normalizers")
    wind = np.asarray(group["static_features"][:, 0], dtype=np.float32)
    values = wind[:, wet]
    wind_mean, wind_scale = float(values.mean()), float(values.std())
    if not np.isfinite(wind_mean) or not np.isfinite(wind_scale) or wind_scale <= 0:
        raise ValueError("invalid Model A wind normalization")
    return mean, scale, wet, wind_mean, wind_scale

class ModelAPairDataset(Dataset):
    """Lazy features and normalized ten-day residual targets for Model A."""

    def __init__(self, dataset_path: str | Path, records: Sequence[tuple[int, int]], *, horizon_days: int = 10) -> None:
        require_model_a_runtime()
        self.dataset_path = Path(dataset_path).resolve()
        self.records = tuple((int(experiment), int(time_index)) for experiment, time_index in records)
        self.horizon_days = int(horizon_days)
        if not self.records:
            raise ValueError("Model A dataset needs at least one pair")
        self._group: Any | None = None
        self._state: Any | None = None
        self._static: Any | None = None
        self._open()

    def _open(self) -> None:
        import zarr

        self._group = zarr.open_consolidated(str(self.dataset_path), mode="r")
        self._state, self._static = self._group["state"], self._group["static_features"]
        self.mean, self.scale, self.wet, self.wind_mean, self.wind_scale = _normalization_from_group(self._group)
        if self._state.shape[2] != STATE_CHANNEL_COUNT or self._static.shape[1] != STATIC_CHANNEL_COUNT:
            raise ValueError("dataset channel count does not match Model A")
        if any(time + self.horizon_days >= self._state.shape[1] for _, time in self.records):
            raise ValueError("a Model A pair exceeds the available trajectory length")

    def __len__(self) -> int:
        return len(self.records)

    def _normalise_state(self, value: np.ndarray) -> np.ndarray:
        result = (value - self.mean[:, None, None]) / self.scale[:, None, None]
        result[:, ~self.wet] = 0.0
        return np.ascontiguousarray(result, dtype=np.float32)

    def __getitem__(self, index: int) -> tuple[Any, Any, Any]:
        experiment, time_index = self.records[index]
        present = self._normalise_state(np.asarray(self._state[experiment, time_index], dtype=np.float32))
        future = self._normalise_state(
            np.asarray(self._state[experiment, time_index + self.horizon_days], dtype=np.float32)
        )
        geometry = np.asarray(self._static[experiment], dtype=np.float32).copy()
        geometry[0] = (geometry[0] - self.wind_mean) / self.wind_scale
        geometry[0, ~self.wet] = 0.0
        features = np.ascontiguousarray(np.concatenate((present, geometry), axis=0), dtype=np.float32)
        return torch.from_numpy(features), torch.from_numpy(future - present), torch.from_numpy(future)

    def __getstate__(self) -> dict[str, Any]:
        state = dict(self.__dict__)
        state["_group"] = state["_state"] = state["_static"] = None
        return state

    def __setstate__(self, state: dict[str, Any]) -> None:
        self.__dict__.update(state)
        self._open()

class ChunkAwareBatchSampler:
    """Shuffle contiguous compressed-Zarr batches while preserving local reads."""

    def __init__(self, dataset: ModelAPairDataset, batch_size: int, seed: int) -> None:
        self.seed, self.epoch = int(seed), 0
        batches: list[tuple[int, ...]] = []
        current: list[int] = []
        previous: int | None = None
        for index, (experiment, _) in enumerate(dataset.records):
            if previous is not None and experiment != previous and current:
                batches.append(tuple(current))
                current = []
            current.append(index)
            if len(current) == batch_size:
                batches.append(tuple(current))
                current = []
            previous = experiment
        if current:
            batches.append(tuple(current))
        self.batches = tuple(batches)

    def __len__(self) -> int:
        return len(self.batches)

    def __iter__(self):
        order = list(range(len(self.batches)))
        random.Random(self.seed + self.epoch).shuffle(order)
        self.epoch += 1
        yield from (list(self.batches[index]) for index in order)

STATE_CHANNEL_COUNT = len(STATE_CHANNELS)

INPUT_CHANNEL_COUNT = STATE_CHANNEL_COUNT + len(STATIC_FEATURES)

