"""Execution step 16: generate the evaluator-only blind forward-response runs.

Plan section 17. The blind geometry/direction manifest -- 216 directions at
days 7,560, 7,920 and 8,280, disjoint centre IDs, unseen vertical
combinations -- was frozen before training and has carried
``numeric_response_present: false`` ever since: "No blind numerical response
or numeric store is generated then. Those forward runs are generated/read
only after every B/C checkpoint, lambda, development report, and ordinary
forward report is frozen and hashed."

That precondition is now satisfied, and this script asserts it explicitly
before doing anything (``assert_precondition``): the lambda selection, all six
training reports, Gate M1 and the step-15 ordinary-forward freeze manifest
must all exist. It refuses to run otherwise, so the blind package cannot be
opened early by accident.

Everything numerical is the step-9 machinery unchanged --
``stage_forward_response_run.run_signed`` and ``run_nominal``, the same pickup
editor, the same frozen amplitudes, the same MITgcm driver -- called with the
blind manifest and the ``blind_test`` role supplied explicitly. That is the
only difference, and it is deliberate: the blind cases must be generated by
exactly the code that generated the development cases, or they would not be a
comparable test.

Section 17: "This package is opened once. A failure is a negative result; it
cannot change the model, checkpoint, response weight, amplitudes, inventory,
or evaluation rule." Nothing here writes to any model, contract or inventory.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Sequence

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "scripts"))
sys.path.insert(0, str(PROJECT_ROOT / "src"))

import stage_forward_response_run as stage  # noqa: E402

BLIND_ROLES = ("blind_test",)
BLIND_INVENTORY = (
    PROJECT_ROOT / "outputs" / "af_fno" / "response" / "forward_response_blind_v1"
    / "forward_response_blind_inventory_v1.jsonl"
)
BLIND_REPORT_ROOT = (
    PROJECT_ROOT / "outputs" / "af_fno" / "response" / "forward_response_blind_v1" / "runs"
)
BLIND_ANCHOR_DAYS = (7560, 7920, 8280)

#: Section 17's precondition, as files that must already exist.
PRECONDITION = {
    "lambda frozen (step 12)": (
        PROJECT_ROOT / "outputs/af_fno/response/forward_response_v1/lambda_screen_v2/lambda_selection_result.json"
    ),
    "Gate M1 frozen (step 14)": (
        PROJECT_ROOT / "outputs/af_fno/response/forward_response_v1/gate_m1/gate_m1_result.json"
    ),
    "ordinary forward frozen (step 15)": (
        PROJECT_ROOT / "outputs/af_fno/response/forward_response_v1/step15_forward_freeze/"
        "step15_forward_freeze_manifest.json"
    ),
}


class BlindRunError(RuntimeError):
    """Raised when the blind package cannot legitimately be generated."""


def assert_precondition() -> dict[str, Any]:
    """Section 17: the blind runs are generated only after every checkpoint,
    lambda, development report and ordinary forward report is frozen."""

    missing = [label for label, path in PRECONDITION.items() if not path.is_file()]
    if missing:
        raise BlindRunError(
            "section 17's precondition is not satisfied -- the blind package may not be "
            f"opened yet. Missing: {'; '.join(missing)}"
        )
    for arm in ("model_c_adjoint_faithful_nominal_control_v1", "model_c_adjoint_faithful_response_v1"):
        for seed in (20260724, 20260911, 20260912):
            report = PROJECT_ROOT / "outputs" / "af_fno" / "C" / arm / f"seed_{seed}" / "report.json"
            if not report.is_file() or json.loads(report.read_text()).get("status") != "complete":
                raise BlindRunError(f"training report is missing or incomplete: {report}")
    lam = json.loads(PRECONDITION["lambda frozen (step 12)"].read_text())
    if lam.get("selected_lambda_resp") is None:
        raise BlindRunError("lambda_resp is not frozen")
    return {
        "precondition_satisfied": True,
        "selected_lambda_resp": lam["selected_lambda_resp"],
        "checked": {label: str(path) for label, path in PRECONDITION.items()},
    }


def load_blind_rows() -> list[dict[str, Any]]:
    return stage.load_production_rows(BLIND_INVENTORY, BLIND_ROLES)


def list_work() -> dict[str, Any]:
    rows = load_blind_rows()
    signed = [
        {
            "regime": r["regime"],
            "day": int(r["anchor_day"]),
            "family": r["family"],
            "slot": int(r["direction_slot"]),
            "horizon_days": int(r["horizon_days"]),
            "direction_id": r["direction_id"],
        }
        for r in rows
    ]
    nominal = [
        {"role": role, "regime": regime, "day": day, "days": days}
        for (role, regime, day), days in sorted(stage.nominal_groups(rows).items())
    ]
    return {
        "inventory": str(BLIND_INVENTORY),
        "roles": list(BLIND_ROLES),
        "signed_directions": len(signed),
        "nominal_branches": len(nominal),
        "signed": sorted(signed, key=lambda r: (r["regime"], r["day"], r["family"], r["slot"])),
        "nominal": nominal,
    }


def run_signed(regime: str, day: int, family: str, slot: int, **kwargs: Any) -> dict[str, Any]:
    assert_precondition()
    return stage.run_signed(
        regime, day, family, slot,
        inventory_path=BLIND_INVENTORY, roles=BLIND_ROLES, report_root=BLIND_REPORT_ROOT, **kwargs,
    )


def run_nominal(regime: str, day: int, **kwargs: Any) -> dict[str, Any]:
    assert_precondition()
    return stage.run_nominal(
        "blind_test", regime, day,
        inventory_path=BLIND_INVENTORY, roles=BLIND_ROLES, report_root=BLIND_REPORT_ROOT, **kwargs,
    )


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest="command", required=True)
    commands.add_parser("precondition")
    commands.add_parser("list-work")
    signed = commands.add_parser("run-signed")
    signed.add_argument("--regime", choices=("S0", "S1", "S2"), required=True)
    signed.add_argument("--day", type=int, choices=BLIND_ANCHOR_DAYS, required=True)
    signed.add_argument("--family", choices=("U", "V", "Theta", "SSH"), required=True)
    signed.add_argument("--slot", type=int, required=True)
    nominal = commands.add_parser("run-nominal")
    nominal.add_argument("--regime", choices=("S0", "S1", "S2"), required=True)
    nominal.add_argument("--day", type=int, choices=BLIND_ANCHOR_DAYS, required=True)
    args = parser.parse_args(argv)

    if args.command == "precondition":
        result: Any = assert_precondition()
    elif args.command == "list-work":
        result = {k: v for k, v in list_work().items() if k not in ("signed",)}
    elif args.command == "run-signed":
        result = run_signed(args.regime, args.day, args.family, args.slot)
    else:
        result = run_nominal(args.regime, args.day)
    print(json.dumps(result, indent=2, sort_keys=True, default=str))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
